name: "Set up environment dependencies"
description: "Set up Conan Cache, Python, Canon and CMake"

runs:
 using: "composite"
 steps:
  - name: Conan Cache
    uses: actions/cache@v3
    env:
      cache-name: cache-conan-modules
    with:
      path: |
        ${{ env.CONAN_USER_HOME }}
        ~/.cache/pip
      key: ${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('conanfile.txt') }}

  - name: Set up Python
    uses: actions/setup-python@v3
    with:
      python-version: 3.7

  - name: Install Conan via PIP
    run: pip install conan --upgrade && conan --version
    shell: bash

  - name: Setup CMake
    uses: jwlawson/actions-setup-cmake@v1.13
    with:
      cmake-version: '3.25.2'
 
