name: Build and Test

on: [push, pull_request, workflow_dispatch]

env:
  # Any call to install method of SystemPackageTool helper should modify the system packages
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-conan-modules
        with:
          path: |
            ${{ env.CONAN_USER_HOME }}
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('conanfile.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install Conan
        run: pip install conan --upgrade && conan --version

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.2'

      - name: Build 
        run: ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-build-folder
          path: "${{ github.workspace }}/build"


  test-matrix:
    needs: build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-conan-modules
        with:
          path: |
            ${{ env.CONAN_USER_HOME }}
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('conanfile.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install Conan
        run: pip install conan --upgrade && conan --version

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.2'

      - uses: actions/download-artifact@v3
        with:
          name: ${{ runner.os }}-build-folder
          path: "${{ github.workspace }}/build"

      - name: Test
        working-directory: build
        # https://cmake.org/cmake/help/latest/manual/ctest.1.html
        run: |
            ctest -C Debug
