name: Build and Test

on: 
  push:
    branches:
      - '**'

  release:
    types: [published]

  workflow_dispatch:

env:
  # Any call to install method of SystemPackageTool helper should modify the system packages
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Build 
        run: ./build.sh

      - name: Artifact (with permissions)
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: build-folder-artifact-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}


  test-matrix:
    needs: build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Artifact (with permissions)
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: build-folder-artifact-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}

      - name: Test
        working-directory: build
        # https://cmake.org/cmake/help/latest/manual/ctest.1.html
        run: |
            ctest -C Debug

      - name: Prepare binaries for release
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: binaries-${{ runner.os }}
          path: ${{ github.workspace }}/build/bin/md5

  release:
    needs: [build-matrix, test-matrix]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: binaries-Linux
          path: ${{ github.workspace }}

      - name: Prepare Linux binaries
        run: |
          mv ${{ github.workspace }}/md5 ${{ github.workspace }}/md5_Linux

      - uses: actions/download-artifact@v3
        with:
          name: binaries-macOS
          path: ${{ github.workspace }}

      - name: Prepare macOS binaries
        run: |
          mv ${{ github.workspace }}/md5 ${{ github.workspace }}/md5_macOS      

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: New Release
          files: |
            ${{ github.workspace }}/md5_Linux
            ${{ github.workspace }}/md5_macOS
